# 上下文
内容|description
---|---
[上下文管理器协议](#上下文管理器协议)|\_\_enter\_\_<br>\_\_exit\_\_
[上下文管理工具](#上下文管理工具)|contextlib


### 上下文管理器协议
```python
class LookingGlass:

    def __enter__(self):
        import sys
        self.original_write = sys.stdout.write
        sys.stdout.write = self.reverse_write
        return 'CCZZPP'  # 一般返回self

    def reverse_write(self, text):
        self.original_write(text[::-1])

    def __exit__(self, exc_type, exc_value, traceback):
        import sys
        sys.stdout.write = self.original_write
        print("out")
        if exc_type is ZeroDivisionError:
            print('Please DO NOT divide by zero!')
            return True


with LookingGlass() as what:
    print('Alice, Kitty and Snowdrop')
print(what)
print("czp")
```

### 上下文管理工具
* @contextmanager:   
yield语句的作用是把函数的定义体分成两部分:   
1.yield语句前面:with块开始时(即解释器调用\_\_enter\_\_方法时)执行   
2.yield 语句后面的代码在 with 块结束时(即调用\_\_exit\_\_方法时)执行

> 上面的class可以改写成以下的方法

```python
import contextlib


@contextlib.contextmanager
def looking_glass():
    import sys
    original_write = sys.stdout.write

    def reverse_write(text):
        original_write(text[::-1])

    sys.stdout.write = reverse_write
    """
    如果不加try-except
    若在 with 块中抛出了异常, Python解释器会将其捕获, 然后在looking_glass函数的yield表达式里再次抛出。
    但是, 那里没有处理错误的代码, 因此 looking_glass函数会中止, 
    永远无法恢复成原来的sys.stdout.write方法, 导致系统处于无效状态
    """
    try:
        yield 'CCZZPP'
    except:
        yield "Error"
    finally:
        sys.stdout.write = original_write


with looking_glass() as what:
    print('Alice, Kitty and Snowdrop')
print(what)
print("czp")
```